name: Django CI/CD

on:
  push:
    branches:
      - homework

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: my_project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug environment variables
        run: |
          echo "Checking environment variables..."
          echo "DB_HOST=${{ secrets.DB_HOST }}"
          echo "DB_NAME=${{ secrets.DB_NAME }}"
          echo "DB_USER=${{ secrets.DB_USER }}"
          echo "DB_PORT=${{ secrets.DB_PORT }}"

      - name: Run tests with SQLite
        working-directory: my_project
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/my_project
            git pull origin main
            docker-compose down
            docker-compose pull  # Обновляем образы, если они изменились

            echo "Waiting for PostgreSQL to be ready..."
            for i in {1..30}; do
              pg_isready -h ${{ secrets.DB_HOST }} -p ${{ secrets.DB_PORT }} -U ${{ secrets.DB_USER }} && break
              echo "PostgreSQL is not ready, retrying..."
              sleep 2
            done

            docker-compose up --build -d

            echo "Running database migrations..."
            docker exec -i my_project_web python manage.py migrate

            echo "Collecting static files..."
            docker exec -i my_project_web python manage.py collectstatic --noinput

            docker system prune -af  # Очищаем старые образы, чтобы не занимали место




